name: CI Checks

on:
  pull_request:
    branches:
      - main

jobs:
  setup-python:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.set-python.outputs.python-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Python version
        id: set-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
        run: echo "python-version=3.11" >> $GITHUB_OUTPUT

  setup-rust:
    runs-on: ubuntu-latest
    outputs:
      rust-version: ${{ steps.set-rust.outputs.rust-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Rust version
        id: set-rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.92.0
          override: true
        run: echo "rust-version=1.92.0" >> $GITHUB_OUTPUT

  black:
    runs-on: ubuntu-latest
    needs: setup-python
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.setup-python.outputs.python-version }}

      - name: Install Black
        run: python -m pip install --upgrade pip && pip install black==24.10.0

      - name: Run Black
        run: black . --check

  flake8:
    runs-on: ubuntu-latest
    needs: setup-python
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.setup-python.outputs.python-version }}

      - name: Install flake8
        run: python -m pip install --upgrade pip && pip install flake8

      - name: Run flake8
        run: flake8

  cargo-fmt:
    runs-on: ubuntu-latest
    needs: setup-rust
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ needs.setup-rust.outputs.rust-version }}
          override: true

      - name: Add rustfmt
        run: rustup component add rustfmt

      - name: Run cargo fmt
        run: cargo fmt -- --check

  cargo-clippy:
    runs-on: ubuntu-latest
    needs: setup-rust
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ needs.setup-rust.outputs.rust-version }}
          override: true

      - name: Add clippy
        run: rustup component add clippy

      - name: Run cargo clippy
        run: cargo clippy --locked --all-targets -- --deny warnings
